all:
	gcc -o palindromic.o palindromic.c -lpthread
	gcc -o matrixSum matrixSum.c -lpthread
	gcc -o matrixSumB matrixSumB.c -lpthread
	gcc -o matrixSumC matrixSumC.c -lpthread

clean:
	rm palindromic.o
