all:
	gcc -o palindromic.o palindromic.c -lpthread
	gcc -o matrixSum.o matrixSum.c -lpthread
	gcc -o matrixSumB.o matrixSumB.c -lpthread
	gcc -o matrixSumC.o matrixSumC.c -lpthread
	gcc -o quicksort.o quicksort_co.c -lpthread

clean:
	rm *.o
